//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Trigger
        {
            get
            {
                return SteamVR_Actions.default_Trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grip
        {
            get
            {
                return SteamVR_Actions.default_Grip;
            }
        }
        
        public virtual SteamVR_Action_Boolean PadTouch
        {
            get
            {
                return SteamVR_Actions.default_PadTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean D_Up
        {
            get
            {
                return SteamVR_Actions.default_D_Up;
            }
        }
        
        public virtual SteamVR_Action_Boolean D_Down
        {
            get
            {
                return SteamVR_Actions.default_D_Down;
            }
        }
        
        public virtual SteamVR_Action_Boolean D_Left
        {
            get
            {
                return SteamVR_Actions.default_D_Left;
            }
        }
        
        public virtual SteamVR_Action_Boolean D_Right
        {
            get
            {
                return SteamVR_Actions.default_D_Right;
            }
        }
        
        public virtual SteamVR_Action_Vector2 PadPosition
        {
            get
            {
                return SteamVR_Actions.default_PadPosition;
            }
        }
        
        public virtual SteamVR_Action_Pose LeftController
        {
            get
            {
                return SteamVR_Actions.default_LeftController;
            }
        }
        
        public virtual SteamVR_Action_Pose RightController
        {
            get
            {
                return SteamVR_Actions.default_RightController;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
