//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_default_Trigger;
        
        private static SteamVR_Action_Boolean p_default_Grip;
        
        private static SteamVR_Action_Boolean p_default_PadTouch;
        
        private static SteamVR_Action_Boolean p_default_D_Up;
        
        private static SteamVR_Action_Boolean p_default_D_Down;
        
        private static SteamVR_Action_Boolean p_default_D_Left;
        
        private static SteamVR_Action_Boolean p_default_D_Right;
        
        private static SteamVR_Action_Vector2 p_default_PadPosition;
        
        private static SteamVR_Action_Pose p_default_LeftController;
        
        private static SteamVR_Action_Pose p_default_RightController;
        
        private static SteamVR_Action_Vibration p_default_Haptic;
        
        public static SteamVR_Action_Boolean default_Trigger
        {
            get
            {
                return SteamVR_Actions.p_default_Trigger.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Grip
        {
            get
            {
                return SteamVR_Actions.p_default_Grip.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_PadTouch
        {
            get
            {
                return SteamVR_Actions.p_default_PadTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_D_Up
        {
            get
            {
                return SteamVR_Actions.p_default_D_Up.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_D_Down
        {
            get
            {
                return SteamVR_Actions.p_default_D_Down.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_D_Left
        {
            get
            {
                return SteamVR_Actions.p_default_D_Left.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_D_Right
        {
            get
            {
                return SteamVR_Actions.p_default_D_Right.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 default_PadPosition
        {
            get
            {
                return SteamVR_Actions.p_default_PadPosition.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Pose default_LeftController
        {
            get
            {
                return SteamVR_Actions.p_default_LeftController.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Pose default_RightController
        {
            get
            {
                return SteamVR_Actions.p_default_RightController.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Vibration default_Haptic
        {
            get
            {
                return SteamVR_Actions.p_default_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.default_Trigger,
                    SteamVR_Actions.default_Grip,
                    SteamVR_Actions.default_PadTouch,
                    SteamVR_Actions.default_D_Up,
                    SteamVR_Actions.default_D_Down,
                    SteamVR_Actions.default_D_Left,
                    SteamVR_Actions.default_D_Right,
                    SteamVR_Actions.default_PadPosition,
                    SteamVR_Actions.default_LeftController,
                    SteamVR_Actions.default_RightController,
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_Trigger,
                    SteamVR_Actions.default_Grip,
                    SteamVR_Actions.default_PadTouch,
                    SteamVR_Actions.default_D_Up,
                    SteamVR_Actions.default_D_Down,
                    SteamVR_Actions.default_D_Left,
                    SteamVR_Actions.default_D_Right,
                    SteamVR_Actions.default_PadPosition,
                    SteamVR_Actions.default_LeftController,
                    SteamVR_Actions.default_RightController};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.default_LeftController,
                    SteamVR_Actions.default_RightController};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.default_Trigger,
                    SteamVR_Actions.default_Grip,
                    SteamVR_Actions.default_PadTouch,
                    SteamVR_Actions.default_D_Up,
                    SteamVR_Actions.default_D_Down,
                    SteamVR_Actions.default_D_Left,
                    SteamVR_Actions.default_D_Right};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.default_PadPosition};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_Trigger,
                    SteamVR_Actions.default_Grip,
                    SteamVR_Actions.default_PadTouch,
                    SteamVR_Actions.default_D_Up,
                    SteamVR_Actions.default_D_Down,
                    SteamVR_Actions.default_D_Left,
                    SteamVR_Actions.default_D_Right,
                    SteamVR_Actions.default_PadPosition};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_default_Trigger = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Default/in/Trigger")));
            SteamVR_Actions.p_default_Grip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Default/in/Grip")));
            SteamVR_Actions.p_default_PadTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Default/in/PadTouch")));
            SteamVR_Actions.p_default_D_Up = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Default/in/D_Up")));
            SteamVR_Actions.p_default_D_Down = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Default/in/D_Down")));
            SteamVR_Actions.p_default_D_Left = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Default/in/D_Left")));
            SteamVR_Actions.p_default_D_Right = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Default/in/D_Right")));
            SteamVR_Actions.p_default_PadPosition = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/Default/in/PadPosition")));
            SteamVR_Actions.p_default_LeftController = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/Default/in/LeftController")));
            SteamVR_Actions.p_default_RightController = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/Default/in/RightController")));
            SteamVR_Actions.p_default_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/Default/out/Haptic")));
        }
    }
}
